#!/bin/bash

(make clean; make)

total=0
totalmax=0

rm -f total.txt *.out

echo
echo Running test cases...

# Test driver
function runtest {
  prog=$1
  args=$2
  testinput=$3
  grade=$4
  inputdescr=
  if [ "$testinput" != "" ]; then
	inputdescr="<$testinput"
  fi
  descr="$prog $args $inputdescr"
  echo
  echo ============ $descr ============
  if [ "$testinput" != "" ]; then
	$prog $args <$testinput > $prog.out
        $prog.org $args <$testinput > $prog.org.out
  else
	$prog $args $testinput > $prog.out
        $prog.org $args $testinput > $prog.org.out
  fi
  
  
  diff $prog.out $prog.org.out > diff.out
  if [ $? -eq 0 ]; then
      echo Test passed...;
      printf "%-56s: %-3d of %-3d\n" "$descr" $grade $grade >> total.txt
      total=`expr $total + $grade`;
  else
      echo "*****Test Failed*****";
      echo
      echo ------ Your Output ----------
      cat $prog.out
      echo
      echo ------ Expected Output ------
      cat $prog.org.out
      echo
      echo ------ Difference -----------
      cat diff.out
      echo -----------------------------
      printf "%-56s: %-3d of %-3d\n" "$descr" 0 $grade >> total.txt
  fi
  totalmax=`expr $totalmax + $grade`;
}

# List of tests running
runtest reverse "" "" 10
runtest reverse "CS240" "" 10
runtest reverse "Purdue University" "" 10
runtest reverse "Department of Computer Science" "" 20
runtest mygrep "" "" 10
runtest mygrep "CS240 Lab" input.txt 10
runtest mygrep "purdue" input.txt 10
runtest mygrep "West" input.txt 20

echo
echo
echo   "-------------------------------------------------------------------"
echo   "CS240: Lab 3 | $USER   "
echo   "-------------------------------------------------------------------"
cat total.txt
echo   "-------------------------------------------------------------------"
echo   "                              			Total: " $total of $totalmax
echo

